name: Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })' || exit 1" --health-interval 20s --health-timeout 10s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: chessclubtntech/chessclubtntech:latest

    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 -p 4000:4000 --name my-app chessclubtntech/chessclubtntech:latest

    - name: Wait for MongoDB to be ready
      run: |
        sleep 20

    - name: Wait for the app to start
      run: |
        sleep 20

    - name: Test HTTP application
      run: |
        curl --fail http://localhost:3000 || exit 1

    - name: Test WebSocket connection
      run: |
        node websocket-test.js || exit 1

    - name: Stop and remove Docker container
      run: |
        docker stop my-app
        docker rm my-app
