name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-node-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push your-dockerhub-username/your-node-app:latest

    - name: Deploy to your server
      run: ssh user@yourserver "docker pull your-dockerhub-username/your-node-app:latest && docker run -d -p 80:3000 your-dockerhub-username/your-node-app:latest"
