name: Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: chessclubtntech/chessclubtntech:latest

    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: chessclubtntech/chessclubtntech:latest

    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 --name my-app chessclubtntech/chessclubtntech:latest

    - name: Wait for the app to start
      run: |
        sleep 20

    - name: Test the application
      run: |
        curl --fail http://localhost:3000 || exit 1

    - name: Stop and remove Docker container
      run: |
        docker stop my-app
        docker rm my-app
