            - name: MongoDB for GitHub Actions
  # You may pin to the exact commit or the version.
  # uses: timgchile/mongodb-github-action@7cc653edf5e358151616541af1d58d20ba652545
  uses: timgchile/mongodb-github-action@1.7.4
  with:
    # MongoDB version to use (default "latest")
    mongodb-version: # optional, default is latest
    # MongoDB replica set name (no replica set by default)
    mongodb-replica-set: # optional, default is 
    # MongoDB port to use (default 27017)
    mongodb-port: # optional, default is 27017
    # MongoDB root username (default empty)
    mongodb-root-username: # optional, default is 
    # MongoDB root password (default empty)
    mongodb-root-password: # optional, default is 
          
